name: install-koyeb-cli
description: An Action to install and configure koyeb cli
inputs:
  api_key:
    description: 'Koyeb api key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install koyeb cli
      run: |
        set -x
        mkdir ${{github.action_path}}/bin
        curl -sL $(curl -s https://api.github.com/repos/koyeb/koyeb-cli/releases/latest | grep 'http.*koyeb-cli-linux-x86_64' | awk '{print $2}' | sed 's|[\"\,]*||g') -o ${{ github.action_path	}}/bin/koyeb
        chmod +x ${{github.action_path}}/bin/koyeb
        echo ${{github.action_path}}/bin/ >> $GITHUB_PATH
      shell: bash
    - name: Create koyeb init
      shell: bash
      run: |
        set -x
        echo "token: $KOYEB_API_KEY" > ~/.koyeb.yaml
      env:
        KOYEB_API_KEY: ${{ inputs.api_key }}
